/**************************************************************
 * Property of MoraSquad-Qtie
 **************************************************************/

#define BLYNK_PRINT Serial    // Comment this out to disable prints and save space
#include <ESP8266WiFi.h>
#include <BlynkSimpleEsp8266.h>
#include <SimpleTimer.h>


char auth[] = "02f74a9b887d4096871ebc1d525ba3e6"; //insert here your token generated by Blynk
// Your WiFi credentials.
char ssid[] = "hansa";
char pass[] = "12345678";
float temp;
int tempPin = 17; // ADC pin

SimpleTimer timer3;

void setup()
{
  Serial.begin(9600); // See the connection status in Serial Monitor
  Blynk.begin(auth, ssid, pass); //insert here your SSID and password

  // Setup a function to be called every second
  timer3.setInterval(1000L, sendUptime);
}

// This function sends Arduino's up time every second to Virtual Pin (5).
// In the app, Widget's reading frequency should be set to PUSH. This means
// that you define how often to send data to Blynk App.
void sendUptime()
{
  // You can send any value at any time.
  // Please don't send more that 10 values per second.
 
  Blynk.virtualWrite(6, temp); // virtual pin 6
}

void loop()
{
  Blynk.run(); // Initiates Blynk
  timer3.run(); // Initiates SimpleTimer
  
   temp = analogRead(tempPin);
   temp = 28 + temp * 0.09765625; // costance (1/1024*100)
  
}
